name: capitalism
version: '${project.version}'
main: de.mymiggi.mc.Capitalism
description: Adds Capitalism to Minecraft
author: Miggi
website: https://mymiggi.de
api-version: '1.20'

commands:
  sell:
    description: "Sell block to earn money"
    usage: "/sell amount block-type"
  buy:
    description: "Buy blocks for money"
    usage: "/buy amount block-type"
  money2:
    description: "Send money to other player"
    usage: "/money2 PlayerName amount"
    #aliases: [cmd, command]
    #permission: permission.node
    #permission-message: "You do not have permission to use this command"